using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BirdScript : MonoBehaviour
{
    public Rigidbody2D myRigidbody;
    public float flapStrength;
    public LogicScript logic;
    public bool birdIsAlive = true;

    // Start is called before the first frame update
    void Start()
    {
        logic = GameObject.FindGameObjectWithTag("Logic").GetComponent<LogicScript>();
    }

    // Update is called once per frame
    void Update()
    {
        // Check for touch input (tap) on the screen
        if ((Input.GetKeyDown(KeyCode.Space) || Input.touchCount > 0 )&& birdIsAlive)
        {
           
                // Apply flap when touch is detected
                myRigidbody.velocity = Vector2.up * flapStrength;
            
        }
    }

    public void OnCollisionEnter2D(Collision2D collision)
    {
        logic.gameOver();
        birdIsAlive = false;
    }
}
